CREATE TABLE PERSON (
	NIF			 CHAR(9)		NOT NULL,
	[NAME]		 VARCHAR(256)	NOT NULL,
	PHONE_NUMBER INT			NOT NULL,
	Constraint PERSON_PK PRIMARY KEY (NIF),
	Constraint PERSON_PH UNIQUE (PHONE_NUMBER)
);


CREATE TABLE ORGANIZER(
    NIF				CHAR(9)			NOT NULL,
    MAIL_ADDRESS    VARCHAR(256)    NOT NULL,
	[PASSWORD]		VARBINARY(128)	NOT NULL,
    Constraint ORGANIZER_PK PRIMARY KEY(NIF),
    Constraint ORGANIZER_UQ UNIQUE (MAIL_ADDRESS)
)


CREATE TABLE STAFF(
    NIF				CHAR(9)     NOT NULL,
    NIF_Organizer   CHAR(9)     NOT NULL,
	PRICE			INT			NOT NULL ,
	STAFF_NUMBER	INT			NOT NULL,
    Constraint STAFF_PK PRIMARY KEY(NIF),
	Constraint CheckPrice CHECK(PRICE > 0),
	FOREIGN KEY (NIF) REFERENCES PERSON(NIF),
	FOREIGN KEY (NIF_Organizer) REFERENCES ORGANIZER(NIF)
)


CREATE TABLE [ROLE](
    ROLE_ID        INT			NOT NULL,
    [DESCRIPTION]    VARCHAR(256) NOT NULL,
    Constraint ROLE_ID_PK PRIMARY KEY(ROLE_ID)
)

CREATE TABLE VENUE(
    [LOCATION]      VARCHAR(256)    NOT NULL,
    NIF_ORGANIZER CHAR(9)         ,
    CAPACITY      INT			  NOT NULL,
    [NAME]        VARCHAR(256)    NOT NULL,
	PRICE		  INT			  NOT NULL,
    CONSTRAINT VENUE_PK PRIMARY KEY(LOCATION),
	CONSTRAINT CheckPriceVenue CHECK(PRICE > 0),
	CONSTRAINT CheckCapacityVenue CHECK(CAPACITY > 0),
    CONSTRAINT VENUE_FK_ORGANIZER FOREIGN KEY(NIF_ORGANIZER) REFERENCES ORGANIZER(NIF)
)


CREATE TABLE FESTIVAL(
    REFERENCE      CHAR(9)		   NOT NULL,
    [NAME]           VARCHAR(256)    NOT NULL,
    GENRE          VARCHAR(128)    NOT NULL,
    [START_DATE]   DATETIME		   NOT NULL,
	END_DATE	   DATETIME		   NOT NULL,
    LOCATION_VENUE VARCHAR(256)    NOT NULL,
    NIF_ORGANIZER    CHAR(9)       NOT NULL,
    Constraint FESTIVAL_PK PRIMARY KEY(REFERENCE),
    Constraint FESTIVAL_FK_ORGANIZER FOREIGN KEY(NIF_ORGANIZER) REFERENCES ORGANIZER(NIF),
	Constraint FESTIVAL_FK_VENUE FOREIGN KEY(LOCATION_VENUE) REFERENCES VENUE(LOCATION)
)

CREATE TABLE ARTIST(
    NIF				CHAR(9)				NOT NULL,
    ARTIST_NAME		VARCHAR(128)		NOT NULL,
	NIF_ORGANIZER	CHAR(9)				NOT NULL,
    Constraint P_NIF_PK PRIMARY KEY(NIF),
	Constraint P_NIF_FK FOREIGN KEY (NIF) REFERENCES PERSON(NIF),
	Constraint O_NIF_FK FOREIGN KEY (NIF_ORGANIZER) REFERENCES ORGANIZER(NIF)
)


CREATE TABLE EQUIPMENT_TYPE(
    [TYPE_ID]		INT					NOT NULL,  
	[TYPE_NAME]		VARCHAR(128)		NOT NULL,
    Constraint TYPE_ID_PK PRIMARY KEY([TYPE_ID]),
)

CREATE TABLE EQUIPMENT(
    RERENCE		INT					NOT NULL,  
	COST		VARCHAR(128)		NOT NULL,
	[NAME]		VARCHAR(128)		NOT NULL,
	[TYPE_ID]	INT					NOT NULL,
	NIF_ARTIST	CHAR(9)				,
    Constraint RERENCE_PK PRIMARY KEY(RERENCE),
	Constraint TYPE_ID_FK FOREIGN KEY ([TYPE_ID]) REFERENCES EQUIPMENT_TYPE([TYPE_ID]),
	CONSTRAINT CheckPriceEquipment CHECK(COST > 0),
	Constraint ART_NIF_FK FOREIGN KEY (NIF_ARTIST) REFERENCES ARTIST(NIF)
)




CREATE TABLE MUSIC(
	[NAME]			VARCHAR(256)		NOT NULL,  
	DURATION		TIME				NOT NULL,
	GENRE			VARCHAR(128)		NOT NULL,
    Constraint NAME_NIF_PK PRIMARY KEY([NAME])
)



CREATE TABLE STAGE(
    STAGE_ID		  INT			  NOT NULL,
    [NAME]			  VARCHAR(256)    NOT NULL,
    CAPCITY			  INT			  NOT NULL,
    LOCATION_VENUE    VARCHAR(256)    NOT NULL,
    CONSTRAINT STAGE_PK PRIMARY KEY(STAGE_ID),
	CONSTRAINT CheckCapacityStage CHECK(CAPCITY > 0),
    CONSTRAINT STAGE_FK_VENUE FOREIGN KEY(LOCATION_VENUE) REFERENCES VENUE(LOCATION)
)



CREATE TABLE WORKS_ON(
    ROLE_ID        INT			NOT NULL,
    STAGE_ID	   INT			NOT NULL,
	NIF			   CHAR(9)		NOT NULL,
	FESTIVAL_REFERENCE	CHAR(9) NOT NULL,
    Constraint WORKS_ON_PK PRIMARY KEY(ROLE_ID,STAGE_ID,NIF,FESTIVAL_REFERENCE),
	CONSTRAINT WORKS_ON_FK_ROLE_ID FOREIGN KEY(ROLE_ID) REFERENCES [ROLE](ROLE_ID),
	CONSTRAINT WORKS_ON_FK_STAGE_ID FOREIGN KEY(STAGE_ID) REFERENCES STAGE(STAGE_ID),
	CONSTRAINT WORKS_ON_FK_NIF FOREIGN KEY(NIF) REFERENCES STAFF(NIF),
	CONSTRAINT WORKS_ON_FK_FESTIVAL FOREIGN KEY (FESTIVAL_REFERENCE) REFERENCES FESTIVAL(REFERENCE)


)


CREATE TABLE CONCERT(
    CONCERT_ID    INT		NOT NULL IDENTITY(1,1),
    STAGE_ID      INT		NOT NULL,
    NIF_ARTIST    CHAR(9)	NOT NULL,
    PRICE         INT		NOT NULL,
    DURATION      TIME      NOT NULL,
	FESTIVAL_REFERENCE CHAR(9) NOT NULL,
    CONSTRAINT CONCERT_PK PRIMARY KEY(CONCERT_ID),
    CONSTRAINT CONCERT_FK_STAGE FOREIGN KEY(STAGE_ID) REFERENCES STAGE(STAGE_ID),
    CONSTRAINT CONCERT_FK_ARTIST FOREIGN KEY(NIF_ARTIST) REFERENCES ARTIST(NIF),
	CONSTRAINT CheckConcertPrice CHECK(PRICE > 0),
	CONSTRAINT CONCERT_FK_FESTIVAL FOREIGN KEY(FESTIVAL_REFERENCE) REFERENCES FESTIVAL(REFERENCE)
)



CREATE TABLE PLAYED(
    NIF			CHAR(9)			NOT NULL,
    [NAME]		VARCHAR(256)	NOT NULL,
    CONSTRAINT PLAYED_PK PRIMARY KEY(NIF,[NAME]),
    CONSTRAINT PLAYED_FK_NIF FOREIGN KEY(NIF) REFERENCES ARTIST(NIF),
    CONSTRAINT PLAYED_FK_NAME FOREIGN KEY([NAME]) REFERENCES MUSIC([NAME]),
)

CREATE TABLE SPONSOR(
    SPONSOR_ID		 INT	NOT NULL IDENTITY(1,1),
    NIF_ORGANIZER    CHAR(9)        ,
    [DESCRIPTION]    VARCHAR(256)	NOT NULL,
    [NAME]			 VARCHAR(256)   NOT NULL,
    CONSTRAINT SPONSOR_PK PRIMARY KEY(SPONSOR_ID),
    CONSTRAINT SPONSOR_FK_ORGANIZER FOREIGN KEY(NIF_ORGANIZER) REFERENCES ORGANIZER(NIF)
)


CREATE TABLE SPONSORS(
    SPONSOR_ID		INT				NOT NULL,
    REFERENCE		CHAR(9)			NOT NULL,
	INVESTMENT		INT				NOT NULL,
    CONSTRAINT SPONSORS_PK PRIMARY KEY(SPONSOR_ID,REFERENCE),
    CONSTRAINT SPONSORS_FK_REF FOREIGN KEY(REFERENCE) REFERENCES FESTIVAL(REFERENCE),
	CONSTRAINT CheckSponsorsInvestment CHECK (INVESTMENT > 0),
    CONSTRAINT SPONSOR_ID FOREIGN KEY(SPONSOR_ID) REFERENCES SPONSOR(SPONSOR_ID),
)



 