CREATE FUNCTION SearchVenue (@NIF char(9)) RETURNS TABLE
AS

	RETURN(SELECT [LOCATION],VENUE.[NAME],CAPACITY, PRICE, COUNT(STAGE_ID) AS NUMBER_OF_STAGES FROM (VENUE JOIN STAGE ON [LOCATION] = LOCATION_VENUE) WHERE NIF_ORGANIZER IS NULL OR NIF_ORGANIZER = @NIF GROUP BY VENUE.[LOCATION],VENUE.[NAME],CAPACITY,PRICE)

GO

CREATE FUNCTION SearchFestival (@NIF CHAR(9)) RETURNS TABLE
AS

	RETURN(SELECT REFERENCE,[NAME] FROM FESTIVAL WHERE NIF_ORGANIZER = @NIF)
GO


CREATE FUNCTION SearchSponsor (@NIF CHAR(9), @Reference CHAR(9)) RETURNS TABLE
AS
	RETURN(SELECT DISTINCT SPONSOR.SPONSOR_ID, SPONSOR.[DESCRIPTION], [NAME] FROM(SPONSOR LEFT OUTER JOIN SPONSORS ON SPONSOR.SPONSOR_ID = SPONSORS.SPONSOR_ID) WHERE SPONSOR.NIF_ORGANIZER = @NIF  AND (REFERENCE != @Reference OR REFERENCE IS NULL));
	
GO


--CREATE FUNCTION SearchOrganizer () RETURNS TABLE
--AS
--	RETURN (SELECT ORGANIZER.NIF,ORGANIZER.MAIL_ADDRESS,PERSON.NAME,PERSON.PHONE_NUMBER FROM (ORGANIZER JOIN PERSON ON ORGANIZER.NIF = PERSON.NIF));

--GO


CREATE FUNCTION GetOrganizerInfo (@OrganizerNIF CHAR(9)) RETURNS TABLE
AS
	
	RETURN(SELECT ORGANIZER.NIF,ORGANIZER.MAIL_ADDRESS,PERSON.NAME,PERSON.PHONE_NUMBER FROM (ORGANIZER JOIN PERSON ON ORGANIZER.NIF = PERSON.NIF) WHERE PERSON.NIF LIKE @OrganizerNIF);
GO


CREATE FUNCTION GetStaffInfo (@OrganizerNIF CHAR(9)) RETURNS TABLE
AS

	RETURN(SELECT PERSON.NIF, PHONE_NUMBER,[NAME],PRICE FROM(STAFF JOIN PERSON ON STAFF.NIF = PERSON.NIF) WHERE NIF_ORGANIZER = @OrganizerNIF);

GO

CREATE FUNCTION GetStages (@Venue VARCHAR(256)) RETURNS TABLE
AS

	RETURN(SELECT * FROM STAGE WHERE LOCATION_VENUE LIKE @Venue)

GO

CREATE FUNCTION GetArtists (@OrganizerNIF CHAR(9),@Reference CHAR(9)) RETURNS TABLE
AS
	RETURN(SELECT NIF, ARTIST_NAME FROM( ARTIST LEFT OUTER JOIN CONCERT ON NIF = NIF_ARTIST) WHERE NIF_ORGANIZER = @OrganizerNIF AND (FESTIVAL_REFERENCE != @Reference OR FESTIVAL_REFERENCE IS NULL))

GO

CREATE FUNCTION GetArtistMusic(@ArtistNIF CHAR(9)) RETURNS TABLE
AS
	RETURN(SELECT MUSIC.[NAME],MUSIC.DURATION,MUSIC.GENRE FROM(MUSIC JOIN PLAYED ON MUSIC.[NAME] = PLAYED.[NAME] JOIN ARTIST ON PLAYED.NIF = ARTIST.NIF) WHERE ARTIST.NIF = @ArtistNIF)
GO

CREATE FUNCTION GetPriceAll (@FestivalReference char(9)) RETURNS INT
AS
   
    BEGIN

    DECLARE @total as INT

    DECLARE @venueTotal as int 
    SELECT @venueTotal=PRICE FROM (FESTIVAL JOIN VENUE ON LOCATION_VENUE = LOCATION) WHERE REFERENCE LIKE @FestivalReference
	
    DECLARE @staffTotal as int 
    SELECT @StaffTotal=sum(PRICE) FROM (FESTIVAL JOIN WORKS_ON ON REFERENCE = FESTIVAL_REFERENCE) JOIN STAFF ON WORKS_ON.NIF = STAFF.NIF GROUP BY REFERENCE HAVING REFERENCE LIKE @FestivalReference

    DECLARE @concertTotal as int 
    SELECT @concertTotal=sum(PRICE) FROM (FESTIVAL JOIN CONCERT ON REFERENCE = FESTIVAL_REFERENCE) GROUP BY REFERENCE HAVING REFERENCE LIKE @FestivalReference

    DECLARE @sponsorTotal as int 
    SELECT @sponsorTotal=sum(INVESTMENT) FROM (FESTIVAL JOIN SPONSORS ON FESTIVAL.REFERENCE = SPONSORS.REFERENCE) GROUP BY FESTIVAL.REFERENCE HAVING FESTIVAL.REFERENCE LIKE @FestivalReference

	if @concertTotal is null
		SET @concertTotal = 0
	if @sponsorTotal is null
		SET @sponsorTotal = 0
	if @venueTotal is null
		SET @venueTotal = 0
	if @staffTotal is null
		SET @staffTotal = 0

    SET @total = @venueTotal + @staffTotal + @concertTotal  - @sponsorTotal
    RETURN @total
    
	END
    
GO

CREATE FUNCTION CheckCredentials (@NIF char(9), @Password VARCHAR(128)) RETURNS INT
AS
   
    BEGIN
	DECLARE @valid as bit;
	DECLARE @PasswordCheckerDec as VARCHAR(128);
	DECLARE @PasswordChecker as VARBINARY(128);
	SELECT @PasswordChecker = [PASSWORD] FROM ORGANIZER WHERE NIF = @NIF;
	SET @PasswordCheckerDec = DecryptByPassPhrase('p2g7', @PasswordChecker)
	IF @PasswordCheckerDec=@Password
		BEGIN
		SET @valid = 1
		END
	ELSE
		BEGIN
		SET @valid = 0
		END

    RETURN @valid
    
	END
    
GO

CREATE FUNCTION GetFestivalMusics(@FestivalReference CHAR(9)) RETURNS TABLE
AS
	RETURN(SELECT DISTINCT MUSIC.[NAME] FROM(FESTIVAL JOIN CONCERT ON FESTIVAL.REFERENCE = CONCERT.FESTIVAL_REFERENCE JOIN ARTIST ON ARTIST.NIF = NIF_ARTIST JOIN PLAYED ON PLAYED.NIF = ARTIST.NIF JOIN MUSIC ON MUSIC.[NAME] = PLAYED.[NAME]) WHERE FESTIVAL_REFERENCE = @FestivalReference);
GO

CREATE FUNCTION FestivalGetAllStaff (@OrganizerNIF CHAR(9),@FestivalReference Char(9)) RETURNS TABLE
AS

	RETURN(SELECT PERSON.NIF, PHONE_NUMBER,PERSON.[NAME],PRICE FROM(STAFF JOIN PERSON ON STAFF.NIF = PERSON.NIF JOIN WORKS_ON ON WORKS_ON.NIF = STAFF.NIF JOIN FESTIVAL ON FESTIVAL.REFERENCE = WORKS_ON.FESTIVAL_REFERENCE) WHERE STAFF.NIF_Organizer = @OrganizerNIF and FESTIVAL_REFERENCE like @FestivalReference);

GO

CREATE FUNCTION FestivalGetAllArtists (@FestivalReference CHAR(9)) RETURNS TABLE
AS

RETURN(SELECT NIF, ARTIST_NAME FROM( ARTIST JOIN CONCERT ON NIF = NIF_ARTIST JOIN FESTIVAL ON FESTIVAL.REFERENCE = CONCERT.FESTIVAL_REFERENCE) WHERE CONCERT.FESTIVAL_REFERENCE = @FestivalReference)

GO

CREATE FUNCTION GetFestivalEquipment (@FestivalReference CHAR(9)) RETURNS TABLE
AS

RETURN(SELECT EQUIPMENT.[NAME], EQUIPMENT_TYPE.[TYPE_NAME],EQUIPMENT.COST FROM (CONCERT JOIN ARTIST ON CONCERT.NIF_ARTIST = ARTIST.NIF JOIN EQUIPMENT ON EQUIPMENT.NIF_ARTIST = ARTIST.NIF JOIN EQUIPMENT_TYPE ON EQUIPMENT_TYPE.[TYPE_ID] = EQUIPMENT.[TYPE_ID]) WHERE CONCERT.FESTIVAL_REFERENCE = @FestivalReference) 

GO

CREATE FUNCTION GetFestivalStages (@FestivalReference CHAR(9)) RETURNS TABLE
AS
RETURN(SELECT STAGE.STAGE_ID,STAGE.CAPCITY,STAGE.[NAME] FROM (FESTIVAL JOIN VENUE ON FESTIVAL.LOCATION_VENUE = VENUE.[LOCATION] JOIN STAGE ON STAGE.LOCATION_VENUE = VENUE.[LOCATION]) WHERE FESTIVAL.REFERENCE = @FestivalReference); 
GO

CREATE FUNCTION GetFestivalSponsors (@FestivalReference CHAR(9)) RETURNS TABLE
AS

RETURN(SELECT SPONSOR.[NAME],SPONSOR.[DESCRIPTION] FROM(SPONSOR JOIN SPONSORS ON SPONSOR.SPONSOR_ID = SPONSORS.SPONSOR_ID JOIN FESTIVAL ON FESTIVAL.REFERENCE = SPONSORS.REFERENCE) WHERE FESTIVAL.REFERENCE = @FestivalReference)

GO

CREATE FUNCTION GetFestivalMainInfo (@Reference CHAR(9)) RETURNS TABLE
AS

RETURN(SELECT [NAME], [START_DATE], END_DATE, LOCATION_VENUE FROM FESTIVAL WHERE REFERENCE = @Reference)