CREATE NONCLUSTERED INDEX ixStaffForeing ON dbo.STAFF (NIF_Organizer);
GO

CREATE NONCLUSTERED INDEX ixStageVenue ON dbo.STAGE (LOCATION_VENUE);
GO

CREATE NONCLUSTERED INDEX ixVenueOrganizer ON dbo.VENUE (NIF_ORGANIZER);
GO

CREATE NONCLUSTERED INDEX ixFestivalOrganizer ON dbo.FESTIVAL (NIF_ORGANIZER);
GO

CREATE NONCLUSTERED INDEX ixConcertFestival ON dbo.CONCERT (FESTIVAL_REFERENCE);
GO

CREATE NONCLUSTERED INDEX ixSponsor ON dbo.SPONSOR (NIF_ORGANIZER);
GO